name: X3_PS.EXE
sha1: 2c2e1c2b1534fe57f976c11a67545e57a7df26cb
options:
  basename: x3_ps.exe
  target_path: disk/eu/D0/X3_PS.EXE
  elf_path: build/x3_ps.exe.elf
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/game
  src_path: src/game

  build_path: build/
  # create_asm_dependencies: True

  ld_script_path: config/ld/game.ld
  ld_dependencies: True

  find_file_boundaries: True
  gp_value: 0x800C9544

  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]
  disasm_unknown: True
  symbol_addrs_path: config/symbols.game.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.game.txt
  undefined_syms_auto_path: config/undefined_syms_auto.game.txt

  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x800, rodata]
      - [0x820, rodata]
      - [0x95C, rodata]
      - [0x980, rodata]
      - [0x130C, rodata]
      - [0x16C0, rodata]
      - [0x179C, rodata]
      - [0x1888, rodata]
      - [0x1C6C, rodata]
      - [0x1C80, rodata]
      - [0x1F60, asm]
      - [0x92210, asm]
      - [0x92220, asm]
      - [0x92230, asm]
      - [0x92240, asm]
      - [0x92250, asm]
      - [0x92260, asm]
      - [0x92270, data]
      - [0xB40E0, data, zero_fill]
  - [0x12E800]
